### ISSUE TITLE
npm install -g music-directory should call nodejs not env node

### ISSUE THREAD

**Issue by ghost** [bahamas10/music-directory#6]
node lives in /usr/sbin/node and is not what the md wants/expects 
man (8) node:
ax25-node - Node front end for AX.25, NET/ROM, Rose and TCP
changing the first line from node to nodejs fixes the problem

**Comment by bahamas10** [comment]
closing issue, marking as won't fix. the official Linux packages from nodejs.org all use a binary named `node`, so that is what this module will support.
